FROM eclipse-temurin:11-jdk-alpine

### Build arguments ###
ARG GCP_SA_KEY_PATH
ARG GCP_DEFAULT_USER_PROJECT_ID
ARG GCP_DEFAULT_USER_DATASET
ARG GCP_DEFAULT_USER_TABLE
ARG GCP_SA_PROJECT_ID
ARG GCP_SA_DATASET
ARG GCP_SA_TABLE
###

### Environment variables ###
# OS
ENV APP_DIR=/usr/local/app
# JVM arguments.
ENV GCP_SA_KEY_PATH=${GCP_SA_KEY_PATH}
ENV GCP_DEFAULT_USER_PROJECT_ID=${GCP_DEFAULT_USER_PROJECT_ID}
ENV GCP_DEFAULT_USER_DATASET=${GCP_DEFAULT_USER_DATASET}
ENV GCP_DEFAULT_USER_TABLE=${GCP_DEFAULT_USER_TABLE}
ENV GCP_SA_PROJECT_ID=${GCP_SA_PROJECT_ID}
ENV GCP_SA_DATASET=${GCP_SA_DATASET}
ENV GCP_SA_TABLE=${GCP_SA_TABLE}
###

# Copy the project into the container.
ADD . ${APP_DIR}

ENTRYPOINT ["sh", "-c", "cd ${APP_DIR} && sh"]
