spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      accept-float-as-int: false
      fail-on-numbers-for-enums: true
      fail-on-unknown-properties: true
    mapper:
      allow-coercion-of-scalars: false
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

bigquery:
  select-all: true
  data-types:
    - STRING
    - DATETIME
    - BOOL
